#ifndef DEVEL_BLADE_EXAMPLE_EXTRA_EXTRA_EXTRA_EXTRA_H_
#define DEVEL_BLADE_EXAMPLE_EXTRA_EXTRA_EXTRA_EXTRA_H_
#pragma once

void ExtraExtra();

#endif  // DEVEL_BLADE_EXAMPLE_EXTRA_EXTRA_EXTRA_EXTRA_H_
